pcall(function() game.GuiRoot.MainMenu:remove() end)
pcall(function() game.GuiRoot.RightPalette:remove() end)
pcall(function() game.GuiRoot.ScoreHud:remove() end)
pcall(function() game.CoreGui.RobloxGui:remove() end)
local plr = game.Players:CreateLocalPlayer(0)
plr.CharacterAppearance = "http://shitblx.cf/Game/CharacterFetch.ashx?ID=2"
plr:LoadCharacter()
--bodyColors = Instance.new("BodyColors", plr.Character)
--bodyColors.HeadColor = BrickColor.new(23)
--bodyColors.TorsoColor = BrickColor.new(26)
--bodyColors.LeftArmColor = BrickColor.new(23)
--bodyColors.RightArmColor = BrickColor.new(26)
--bodyColors.LeftLegColor = BrickColor.new(23)
--bodyColors.RightLegColor = BrickColor.new(26)